sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 47.102.128.67
    port: 3306
    database: sky_take_out
    username: root
    password: 123456

  minio:
    access-key: minioadmin
    secret-key: minioadmin
    endpoint: 47.102.128.67:9000
    bucket: cangqiongwaimai
    read-path: 47.102.128.67:9000

