sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 47.102.128.67
    port: 3306
    database: sky_take_out
    username: root
    password: 123456

  minio:
    access-key: yxm
    secret-key: yxm980918
    endpoint: http://47.102.128.67:19000
    bucket: cangqiongwaimai
    read-path: http://47.102.128.67:19000

  redis:
    host: 47.102.128.67
    port: 6379
    database: 10

  wechat:
    appid: wx7c01f92a8aa18010
    secret: 11a6bf42f8ba5ff581ff38f92e3d4e14
    mchid: 12345678
    mch-serial-no: FAKENUMBER
    private-key-file-path: D:\pay\fakepath.pem
    api-v3-key: FAKEKEY
    we-chat-pay-cert-file-path:
    notify-url: https://localhost:8080/notify/paySuccess
    refund-notify-url: https://localhost:8080/notify/refundSuccess



